// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonetisV2.Server.Models;

#nullable disable

namespace MonetisV2.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250324033713_SeedExpenses")]
    partial class SeedExpenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MonetisV2.Shared.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 4.50m,
                            Category = "Food",
                            Date = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 30.00m,
                            Category = "Transport",
                            Date = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Gas"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 80.75m,
                            Category = "Food",
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Groceries"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 12.99m,
                            Category = "Entertainment",
                            Date = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Netflix"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 25.00m,
                            Category = "Education",
                            Date = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Books"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
